### ISSUE TITLE
Ability to search for the sound would be great!

### ISSUE THREAD

**Issue by axelonet** [holt-soundboard/holt-soundboard-mobile#1]
Absolutely the best one from all the _Gina Lenneti saying Toilet Emoji_ ones out there! It would be even better if it had a search functionality to find the right one at the right time.

**Comment by ninest** [comment]
Hi, thanks for creating the issue, but I likely won't be working on the all any longer. The app has also been removed from the play store since April.

I suggest saving the sound to your favorites For faster access
